version: '2'
services:
    aioria-app:
        image: aioria
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://aioria-mysql:3306/aioria?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    aioria-mysql:
        extends:
            file: mysql.yml
            service: aioria-mysql
